export const HTTP_ERROR_FILTER = 'HTTP_ERROR_FILTER';
export const HTTP_SYSTEM_ERROR_HANDLER = 'HTTP_SYSTEM_ERROR_HANDLER';
export const HTTP_BEFORE_REQUEST = 'HTTP_BEFORE_REQUEST';
export const HTTP_BEFORE_RESPONSE = 'HTTP_BEFORE_RESPONSE';
export const HTTP_AFTER_RESPONSE = 'HTTP_AFTER_RESPONSE';

export const HTTP_CONTEXT_TYPE = 'http';
